### ISSUE TITLE
Kuma CLI

### ISSUE THREAD

**Issue by lordlightman** [BigBoot/AutoKuma#100]
Hello. Thank you for your awesome work on a project.

I was wondering if you can help me figure out how to use kuma CLI. I am running Autokuma as a Docker container on my RPI 5. Here is my config:

```
autokuma:
    image: ghcr.io/bigboot/autokuma:0.8.0
    container_name: uptime-kuma-labels
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./autokuma:/data
    environment:
      AUTOKUMA__KUMA__URL: https://example.com
      AUTOKUMA__KUMA__USERNAME: <username>
      AUTOKUMA__KUMA__PASSWORD: <password>
      AUTOKUMA__DEFAULT_SETTINGS: |-
        http.expiryNotification: false
        docker.docker_host: 1
```

Here is what I get when I try to obtain a list of monitors:

```
docker compose exec autokuma kuma monitor list
OCI runtime exec failed: exec failed: unable to start container process: exec: "kuma": executable file not found in $PATH: unknown
```
