### ISSUE TITLE
Use traefik labels as label prefix

### ISSUE THREAD

**Issue by Disane87** [BigBoot/AutoKuma#105]
Hi and thank you for this awesome project!

I have several services running with one or more available webservers. Since I have around 30 docker containers running, I don't want to edit all of them manually and I tried to link autokuma with the traefik tags, because all available service have traefik tags.

Here are some of my tags
```docker
- traefik.enable=true
- traefik.subdomain=status
- traefik.http.services.uptimekuma.loadbalancer.server.port=3001
```

`traefik.subdomain` is a custom tag to get rid of the boilerplate I have to set on each service for Traefik.

But when I set `AUTOKUMA__DOCKER__LABEL_PREFIX` to `traefik` autokuma throws exceptions like

> WARN [kuma_client::util] Error while parsing http: unknown variant `services`, expected one of `group`, `http`, `port`, `ping`, `keyword`, `json-query`, `grpc-keyword`, `dns`, `docker`, `real-browser`, `push`, `steam`, `gamedig`, `mqtt`, `kafka-producer`, `sqlserver`, `postgres`, `mysql`, `mongodb`, `radius`, `redis`, `tailscale-ping`!
WARN [autokuma::sync] Encountered error during sync: Error while trying to parse labels: unknown variant `services`, expected one of `group`, `http`, `port`, `ping`, `keyword`, `json-query`, `grpc-keyword`, `dns`, `docker`, `real-browser`, `push`, `steam`, `gamedig`, `mqtt`, `kafka-producer`, `sqlserver`, `postgres`, `mysql`, `mongodb`, `radius`, `redis`, `tailscale-ping`

Which I understand, because the `traefik` tags doesn't match your `kuma.xyz` syntax.

Do you have any idea how I can automatically create entries in UptimeKuma with these treafik labels?

**Comment by BigBoot** [comment]
Not possible, you could create a snippet to "translate" traefik labels to autokuma ones to decrease duplication, but you'd still need to add a label to include the snippet in the given containers.

**Comment by Disane87** [comment]
Too bad! 

Is there a chance to get such a "mode" or is this a thing you don't want to support?

**Comment by lukanvanderlinde** [comment]
I loved the idea

**Comment by BigBoot** [comment]
A "traefik mode" is not possible since traefik uses multiple sources of information, i.e. the config file/env variables etc, the labels just don't contain all of the information. However I've added the ability to create snippets without the "kuma." prefix, this will allow creating a snippet tailored to whatever setup you have, see [!Snippets](https://github.com/BigBoot/AutoKuma?tab=readme-ov-file#snippets)

**Comment by Disane87** [comment]
> A "traefik mode" is not possible since traefik uses multiple sources of information, i.e. the config file/env variables etc, the labels just don't contain all of the information. However I've added the ability to create snippets without the "kuma." prefix, this will allow creating a snippet tailored to whatever setup you have, see [!Snippets](https://github.com/BigBoot/AutoKuma?tab=readme-ov-file#snippets)

That looks awesome @BigBoot will test it soon! Thank you!

**Comment by ryanwinter** [comment]
Wait, was this just added? I was trying to use this feature and it didnt seem to work, but I guess it isnt release yet.

**Comment by ryanwinter** [comment]
Was this just added? I was trying to get it to work and it didnt appear to be doing anything, I guess its not in the 0.8 release :)

**Comment by ryanwinter** [comment]
Just updated and configured this, works awesomely! Now I just need to enable the traefik label and it automatically created the autokuma using my customer snippet. Thanks :)

**Comment by johntdyer** [comment]
This sounds like a super interesting and handy feature but its not really clear to me from the small section in the docs how one would actually use it...  At least not for me and my pea sized brain :)

**Comment by johntdyer** [comment]
@BigBoot  - thanks for getting back to me.... I guess what I am looking for here is a most complete practical example of how this feature might be used.  I felt that was kind of lacking with whats currently provided.... Hope that makes sense

**Comment by ryanwinter** [comment]
Here is an example of what I have done for homepage.

## Create a traefik snippet

The following snippet overrides the default rule for a docker provider. It lets me override host and domain if I want, but otherwise falls back to defaults.

```yaml
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    defaultRule: "Host(`\
      {{ if (index .Labels \"service.host\") }}\
        {{ index .Labels \"service.host\" }}\
      {{ else }}\
        {{ .ContainerName }}\
      {{ end }}\
      {{ if (index .Labels \"service.domain\") }}\
        .{{ index .Labels \"service.domain\" }}\
      {{ else }}\
        .example.com\
      {{ end }}`)"
    exposedByDefault: false
```

## Create autokuma snippet

Then in my autokuma's `config.yaml` I have the following snippet which to create the monitor and group (optional)

```yaml
snippets:
  "!traefik.enable": |
    {% set label = container.Labels %}
    {{ label["service.host"] }}.http.name: {{ label["service.host"] }}
    {{ label["service.host"] }}.http.url: https://{{ label["service.host"] }}
    {%- if label["service.domain"] %}.{{ label["service.domain"] }}{% else %}.example.com{% endif %}
    {%- if label["service.path"] %}/{{ label["service.path"] }}{% endif %}
    {% if label["service.group"] %}
      {{ label["service.group"] }}.group.name: {{ label["service.group"] }}
      {{ label["service.host"] }}.http.parent_name: {{ label["service.group"] }}
    {% endif %}
```

## Define my service

Now in my compose file for a service, I can define `service.host`, `service.domain` and `service.group`. This is only triggered if `traefik.enable` is defined. The is because I only want uptime kuma to run on enabled traefik services.

```yaml
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    volumes:
      - config:/app/config
    labels:
      service.host: "home"
      service.group: "apps"
      traefik.enable: "true"

volumes:
  config:
```

**Comment by Disane87** [comment]
@ryanwinter I don't get it working, it seems my autokuma ignores my config file. Could you send me your compose file or commands to execute the container? Want to doublecheck my docker against yours. Thank you in advance!

**Comment by fanpenghuix** [comment]
I followed this configuration and nothing happened. I didn't see the containers,  no errors, and not even any log output. some of my config below:

- service compose:
```
services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    restart: "always"
    privileged: true
    security_opt:
      - label=disable
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      service.host: home
      service.group: apps
      traefik.http.routers.homepage.middlewares: authelia@file
      homepage.group: Services
      homepage.name: Dockerproxy(3)
      homepage.icon: docker
```
- auto-kuma compose
```
services:
  autokuma:
    image: ghcr.io/bigboot/autokuma:latest
    container_name: autokuma
    restart: unless-stopped

    environment:
      AUTOKUMA__KUMA__URL: http://192.168.101.3:3001
      AUTOKUMA__KUMA__USERNAME: admin
      AUTOKUMA__KUMA__PASSWORD: {password}
      AUTOKUMA__DOCKER__HOSTS: tcp://192.168.101.3:2375;tcp://192.168.101.4:2375
      AUTOKUMA__SYNC__DELETE: "true"
      AUTOKUMA__DEFAULTS__HTTP__INTERVAL: 60
      AUTOKUMA__SNIPPETS__!SERVICE.HOST: |-
        {% set label = container.Labels %}
        {{ label["service.host"] }}.http.name: {{ label["service.host"] }}
        {{ label["service.host"] }}.http.url: https://{{ label["service.host"] }}
        {%- if label["service.domain"] %}.{{ label["service.domain"] }}{% else %}.example.com{% endif %}
        {%- if label["service.path"] %}/{{ label["service.path"] }}{% endif %}
        {% if label["service.group"] %}
          {{ label["service.group"] }}.group.name: {{ label["service.group"] }}
          {{ label["service.host"] }}.http.parent_name: {{ label["service.group"] }}
        {% endif %}
    volumes:
      - ./autokuma-data:/data
```

If I use kuma.__<snippets>, everything works fine, but this is not what I want.

**Comment by BigBoot** [comment]
label names are case sensitive, if your label is called `service.host`, then you need to called the !Snippet the same, i.e.:

```yaml
      AUTOKUMA__SNIPPETS__!service.host: |-
        {% set label = container.Labels %}
        {{ label["service.host"] }}.http.name: {{ label["service.host"] }}
        {{ label["service.host"] }}.http.url: https://{{ label["service.host"] }}
        {%- if label["service.domain"] %}.{{ label["service.domain"] }}{% else %}.example.com{% endif %}
        {%- if label["service.path"] %}/{{ label["service.path"] }}{% endif %}
        {% if label["service.group"] %}
          {{ label["service.group"] }}.group.name: {{ label["service.group"] }}
          {{ label["service.host"] }}.http.parent_name: {{ label["service.group"] }}
        {% endif %}
```

**Comment by fanpenghuix** [comment]
> label names are case sensitive, if your label is called `service.host`, then you need to called the !Snippet the same, i.e.:
> 
>       AUTOKUMA__SNIPPETS__!service.host: |-
>         {% set label = container.Labels %}
>         {{ label["service.host"] }}.http.name: {{ label["service.host"] }}
>         {{ label["service.host"] }}.http.url: https://{{ label["service.host"] }}
>         {%- if label["service.domain"] %}.{{ label["service.domain"] }}{% else %}.example.com{% endif %}
>         {%- if label["service.path"] %}/{{ label["service.path"] }}{% endif %}
>         {% if label["service.group"] %}
>           {{ label["service.group"] }}.group.name: {{ label["service.group"] }}
>           {{ label["service.host"] }}.http.parent_name: {{ label["service.group"] }}
>         {% endif %}

still not works, and only see ascii logo in logs, any suggestions?
```
services:
  autokuma:
    image: ghcr.io/bigboot/autokuma:latest
    container_name: autokuma
    restart: unless-stopped
    environment:
      AUTOKUMA__KUMA__URL: http://192.168.101.3:3001
      AUTOKUMA__KUMA__USERNAME: admin
      AUTOKUMA__KUMA__PASSWORD: pwd
      AUTOKUMA__DOCKER__HOSTS: tcp://192.168.101.3:2375;tcp://192.168.101.4:2375
      AUTOKUMA__SYNC__DELETE: "true"
      AUTOKUMA__DEFAULTS__HTTP__INTERVAL: 60
      AUTOKUMA__SNIPPETS__!homepage: |-
        {% set label = container.Labels %}
        {{ label["homepage.name"] }}.http.name: {{ label["homepage.name"] }}
        {{ label["homepage.href"] }}.http.url: https://{{ label["homepage.href"] }}
    volumes:
      - ./autokuma-data:/data
```
```
services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    restart: "always"
    privileged: true
    security_opt:
      - label=disable
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - homepage.group=Services
      - homepage.name=Dockerproxy(3)
      - homepage.icon=docker
      - homepage.href=http://192.168.101.3:2375
```

**Comment by BigBoot** [comment]
You service doesn't have a label called `homepage` use `homepage.name` (or some of the other existing labels) `AUTOKUMA__SNIPPETS__!homepage.name: ...`

**Comment by fanpenghuix** [comment]
> You service doesn't have a label called `homepage` use `homepage.label` (or some of the other existing labels) `AUTOKUMA__SNIPPETS__!homepage.label: ...`

Yes, I noticed it before. Now that it has been changed like this, it still doesn't work.

```
services:
  autokuma:
    image: ghcr.io/bigboot/autokuma:latest
    container_name: autokuma
    restart: unless-stopped

    environment:
      AUTOKUMA__KUMA__URL: http://192.168.101.3:3001
      AUTOKUMA__KUMA__USERNAME: admin
      AUTOKUMA__KUMA__PASSWORD: Admin@123456.
      AUTOKUMA__DOCKER__HOSTS: tcp://192.168.101.3:2375;tcp://192.168.101.4:2375
      AUTOKUMA__SYNC__DELETE: "true"
      AUTOKUMA__DEFAULTS__HTTP__INTERVAL: 60
      AUTOKUMA__SNIPPETS__!homepage.name: |-
        {% set label = container.Labels %}
        {{ label["homepage.name"] }}.http.name: {{ label["homepage.name"] }}
        {{ label["homepage.href"] }}.http.url: https://{{ label["homepage.href"] }}
    volumes:
      - ./autokuma-data:/data
```

**Comment by fanpenghuix** [comment]
> You service doesn't have a label called `homepage` use `homepage.name` (or some of the other existing labels) `AUTOKUMA__SNIPPETS__!homepage.name: ...`

BTW, I think the main problem at present is the lack of logs. I can hardly determine what exactly happened. Is there an option for log levels?

**Comment by BigBoot** [comment]
Yes you can increase logging with `RUST_LOG: 'autokuma=debug'`, though I don't think you'll get anything useful here.

**Comment by BigBoot** [comment]
I think the problem is actually that ! is not valid for env variables and docker just silently ignores the invalid name

**Comment by fanpenghuix** [comment]
> Yes you can increase logging with `RUST_LOG: 'autokuma=debug'`, though I don't think you'll get anything useful here.

Yes, no useful logs, I tried to config as below, I can see the container in uptime kuma, It seems AUTOKUMA__SNIPPETS__! homepage.name does not function as expected.

```
services:
  autokuma:
    image: ghcr.io/bigboot/autokuma:latest
    container_name: autokuma
    restart: unless-stopped

    environment:
      RUST_LOG: 'kuma_client=debug,autokuma=debug'
      AUTOKUMA__KUMA__URL: http://192.168.101.3:3001
      AUTOKUMA__KUMA__USERNAME: admin
      AUTOKUMA__KUMA__PASSWORD: Admin@123456.
      AUTOKUMA__DOCKER__HOSTS: tcp://192.168.101.3:2375;tcp://192.168.101.4:2375
      AUTOKUMA__SYNC__DELETE: "true"
      AUTOKUMA__DEFAULTS__HTTP__INTERVAL: 60
      AUTOKUMA__SNIPPETS__APP: |-
        {% set label = container.Labels %}
        {{ label["homepage.name"] }}.http.name: {{ label["homepage.name"] }}
        {{ label["homepage.href"] }}.http.url:  {{ label["homepage.href"] }}
    volumes:
      - ./autokuma-data:/data
```
```
..
labels:
      - homepage.group="Services"
      - homepage.name="Dockerproxy(3)"
      - homepage.icon="docker"
      - homepage.href="http://192.168.101.3:2375"
      - kuma.__app="dockerproxy"
```

**Comment by fanpenghuix** [comment]
> I think the problem is actually that ! is not valid for env variables and docker just silently ignores the invalid name

From the container, it can be seen that the environment variables have been set correctly(I  tried to change compose.yml)
```
root@78798e3c93f5:/# env
AUTOKUMA__SNIPPETS__!APP={% set label = container.Labels %}
{{ label["homepage.name"] }}.http.name: {{ label["homepage.name"] }}
{{ label["homepage.href"] }}.http.url:  {{ label["homepage.href"] }}
HOSTNAME=78798e3c93f5
PWD=/
AUTOKUMA__KUMA__USERNAME=admin
AUTOKUMA_DOCKER=1
HOME=/root
AUTOKUMA__KUMA__URL=http://192.168.101.3:3001
TERM=xterm
AUTOKUMA__SYNC__DELETE=true
SHLVL=1
AUTOKUMA__DEFAULTS__HTTP__INTERVAL=60
AUTOKUMA__DOCKER__HOSTS=tcp://192.168.101.3:2375;tcp://192.168.101.4:2375
AUTOKUMA__KUMA__PASSWORD=**********
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUST_LOG=kuma_client=debug,autokuma=debug
_=/usr/bin/env
```

**Comment by BigBoot** [comment]
@fanpenghuix I've identified the problem, the config library is unable to parse environment variables with `!` or `.` in the name, so for now you won't be able to define !Snippets using env variables.

**Comment by fanpenghuix** [comment]
> [@fanpenghuix](https://github.com/fanpenghuix) I've identified the problem, the config library is unable to parse environment variables with `!` or `.` in the name, so for now you won't be able to define !Snippets using env variables.

I move snippets in the config.toml file, but it seems they didn't work either. 
```
volumes:
      - ./autokuma-data/config.toml:/root/.config/autokuma/config/autokuma.toml
      - ./autokuma-data:/data
```
```
[snippets]
'!homepage.name' = '''
  {% set label = container.Labels %}
  {{ label["homepage.name"] }}.http.name: {{ label["homepage.name"] }}
  {{ label["homepage.href"] }}.http.url:  {{ label["homepage.href"] }}
'''
```

**Comment by BigBoot** [comment]
The path for the config should be `/root/.config/autokuma/config.toml`

**Comment by fanpenghuix** [comment]
> The path for the config should be `/root/.config/autokuma/config.toml`

Yes, it works. Btw, there is a minor mistake here(https://github.com/BigBoot/AutoKuma/blame/master/README.md#L163). It should be named "config.toml".

**Comment by arcoast** [comment]
Thought I'd just post my config here in case it helps others, it sets up monitoring in Uptime Kuma using a combination of my [Homepage labels](https://gethomepage.dev/) and Traefik labels, organised like this:

```yaml
.
├── Authoring (Homepage Category)
│   ├── Nextcloud
│   │   ├── Nextcloud (External)
│   │   ├── Nextcloud (Internal)
│   │   └── Nextcloud (Docker)
│   └── Hedgedoc
│       ├── Hedgedoc (External)
│       ├── Hedgedoc (Internal)
│       └── Hedgedoc (Docker)
└── Infrastructure (Homepage Category)
    ├── Apprise
    │   ├── Apprise (External)
    │   ├── Apprise (Internal)
    │   └── Apprise (Docker)
    └── Unifi
        ├── Unifi (External)
        ├── Unifi (Internal)
        └── Unifi (Docker)
```

Here's an example of a container and it's labels

```yaml
services:
    nextcloud:
        image: lscr.io/linuxserver/nextcloud
        container_name: nextcloud
        labels:
            - "autokuma.internal=true"
            - "autokuma.external=true"
            - "autokuma.docker=true"
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.services.nextcloud.loadbalancer.server.scheme=https"
            - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
            - "traefik.http.routers.nextcloud.entrypoints=websecure"
            - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)"
            - "traefik.http.routers.nextcloud.middlewares=nextcloud-secure-headers@file, nextcloud-redirect@file"          
            - "homepage.group=Authoring"
            - "homepage.name=nextcloud"
            - "homepage.icon=https://icons.${DOMAIN}/nextcloud"
            - "homepage.href=https://nextcloud.${DOMAIN}/"
            - "homepage.description=File Sharing"
```

AutoKuma is installed as follows

```yaml
services:
    autokuma:
        image: ghcr.io/bigboot/autokuma:latest
        container_name: autokuma
        networks:
            - traefik
        volumes:
            - ${DEPLOY}/autokuma/autokuma/data:/data
            - ${DEPLOY}/autokuma/autokuma/config.toml:/root/.config/autokuma/config.toml
        restart: unless-stopped
```

My `config.toml` file is as follows:

```toml
[kuma]
url = "http://uptime-kuma:3001/"

[docker]
enabled = true
source = "container"
label_prefix = "kuma"
hosts = "http://docker-socket-proxy:2375"


[files]
enabled = true
follow_symlinks = false

[kubernetes]
enabled = false

[snippets]
"!autokuma.docker" = '''
{% if args[0] == "true" %}
    {% set label = container["Labels"] %}

    {# Setup docker host #}
    {% set sysname = system_info['Name'] %}
    {{sysname}}.docker_host.name: {{ sysname }}
    
    {# Assumes presence of a docker socket proxy container that is accessible #}
    {{sysname}}.docker_host.connection_type: tcp
    {{sysname}}.docker_host.path: "http://docker-socket-proxy:2375"
    
    {# Setup root groups based on homepage category #}
    {% set root_group_key = "homepage.group" %}
    {% set root_group = container["Labels"][root_group_key] %}
    {{ root_group }}.group.name: {{ root_group }}
    
    {# Create a subgroup for this container under root group #}
    {{ container_name }}.group.name: {{ container_name }}
    {{ container_name }}.group.parent_name: {{ root_group }}

    {# Setup docker host & container name based on homepage name #}
    {{ container_name }}_docker.docker.docker_host_name: {{ sysname }}
    {{ container_name }}_docker.docker.name: "{{ label["homepage.name"] }} (docker)"
    {{ container_name }}_docker.docker.parent_name: {{ container_name }}
    {{ container_name }}_docker.docker.docker_container: {{ container_name }}

{% endif %}
'''

"!autokuma.external" = '''
{% if args[0] == "true" %}

    {% set label = container["Labels"] %}

    {# Setup root groups based on homepage category #}
    {% set root_group_key = "homepage.group" %}
    {% set root_group = container["Labels"][root_group_key] %}
    {{ root_group }}.group.name: {{ root_group }}
    
    {# Create a subgroup for this container under root group #}
    {{ container_name }}.group.name: {{ container_name }}
    {{ container_name }}.group.parent_name: {{ root_group }}
    
    {# Setup external URL based on homepage href #}
    {{ container_name }}_external_http.http.name: "{{ label["homepage.name"] }} (http - external)"
    {{ container_name }}_external_http.http.parent_name: {{ container_name }}
    {{ container_name }}_external_http.http.url: {{ label["homepage.href"] }}
{% endif %}
'''

"!autokuma.internal" = '''
{% if args[0] == "true" %}
    {% set label = container["Labels"] %}

    {# Check if container is using https, if so set appropriately and ignore TLS #}
    {% set https_key = "traefik.http.services." ~ container_name ~ ".loadbalancer.server.scheme" %}
        {% if https_key in container["Labels"] %}
            {% set https = container["Labels"][https_key] %}
            {{ container_name }}_internal_http.http.ignore_tls: true
        {% else %}
            {% set https = "http" %}
        {% endif %}

    {# Extract port number from Traefik config #}
    {% set port_key = "traefik.http.services." ~ container_name ~ ".loadbalancer.server.port" %}
    {% set port = container["Labels"][port_key] %}

    {# Setup root groups based on homepage category #}
    {% set root_group_key = "homepage.group" %}
    {% set root_group = container["Labels"][root_group_key] %}
    {{ root_group }}.group.name: {{ root_group }}
    
    {# Create a subgroup for this container under root group #}
    {{ container_name }}.group.name: {{ container_name }}
    {{ container_name }}.group.parent_name: {{ root_group }}
    
    {# Setup internal URL #}
    {{ container_name }}_internal_http.http.name: "{{ label["homepage.name"] }} (http - internal)"
    {{ container_name }}_internal_http.http.parent_name: {{ container_name }}
    {{ container_name }}_internal_http.http.url: {{ https }}://{{ container_name }}:{{ port }}
{% endif %}

{# For VPN use set autokuma.internal to name of VPN container #}
{% if args[0] != "true" %}
    {% set label = container["Labels"] %}

    {# Check if container is using https, if so set appropriately and ignore TLS#}
    {% set https_key = "traefik.http.services." ~ container_name ~ ".loadbalancer.server.scheme" %}
        {% if https_key in container["Labels"] %}
            {% set https = container["Labels"][https_key] %}
            {{ container_name }}_internal_http.http.ignore_tls: true
        {% else %}
            {% set https = "http" %}
        {% endif %}

    {# Extract port number from Traefik config#}
    {% set port_key = "traefik.http.services." ~ container_name ~ ".loadbalancer.server.port" %}
    {% set port = container["Labels"][port_key] %}

    {# Setup root groups based on homepage category #}
    {% set root_group_key = "homepage.group" %}
    {% set root_group = container["Labels"][root_group_key] %}
    {{ root_group }}.group.name: {{ root_group }}
    
    {# Create a subgroup for this container under root group #}
    {{ container_name }}.group.name: {{ container_name }}
    {{ container_name }}.group.parent_name: {{ root_group }}
    
    {# Setup internal URL #}
    {{ container_name }}_internal_http.http.name: "{{ label["homepage.name"] }} (http - internal)"
    {{ container_name }}_internal_http.http.parent_name: {{ container_name }}
    {{ container_name }}_internal_http.http.url: {{ https }}://{{ args[0] }}:{{ port }}
{% endif %}
'''
```

You can choose which monitors to apply per container by setting these labels:

```yaml
        labels:
            - "autokuma.internal=true"
            - "autokuma.external=true"
            - "autokuma.docker=true"
```


I have some containers routed over a VPN which breaks the internal http check in Uptime-Kuma so for these instead of setting 

```yaml
        labels:
            - "autokuma.internal=true"
```

instead set it to the name of the VPN container

```yaml
        labels:
            - "autokuma.internal=vpn-container"
``` 

Also note that
```yaml
        labels:
            - "autokuma.docker=true"
```
Assumes the presence of a docker socket proxy container called `docker-socket-proxy` and using port `2375` without TLS.  I'm using the [linuxserver.io version here](https://github.com/linuxserver/docker-socket-proxy)

I'm not an IT guy or a dev, and only been playing with this for a few hours so far so go easy on me, but I can see it's generated a lot of confusion so thought I'd post my setup in the hope it helps others.

I'm looking forward to the [environmental variables for snippets to be fixed](https://github.com/BigBoot/AutoKuma/issues/171) so I can dispense with the toml config.

Loving AutoKuma, I'd never been bothered to setup Uptime Kuma in the past as I couldn't face all the GUI config, so thanks @BigBoot for making this and the [playground](https://autokuma-playground.bigboot.dev/) and the [entities list](https://github.com/BigBoot/AutoKuma/blob/master/ENTITY_TYPES.md) was so useful!

Thanks to @ryanwinter too, his setup was really useful to get my head around how the templating works.
