### ISSUE TITLE
Failed to load docker host config

### ISSUE THREAD

**Issue by zmoerema** [BigBoot/AutoKuma#108]
Hello,

I am setting up AutoKuma to work alongside Uptime-Kuma. While AutoKuma successfully adds monitors to Uptime-Kuma, it doesn’t configure the Docker host correctly. If you have any insights or suggestions to fix this issue, I’d greatly appreciate your help!

Below are the Docker Compose configurations for both AutoKuma and Uptime-kuma:

```
autokuma:
    image: ghcr.io/bigboot/autokuma:latest
    container_name: autokuma
    environment:
      AUTOKUMA__KUMA__URL: http://192.168.1.100:3001
      AUTOKUMA__KUMA__USERNAME: admin
      AUTOKUMA__KUMA__PASSWORD: password
      AUTOKUMA__DEFAULT_SETTINGS: |-
        docker.docker_container: {{container_name}}
        http.max_redirects: 10
        *.max_retries: 3
      AUTOKUMA__SNIPPETS__DOCKER: |-
        {{container_name}}_docker.docker.name: {{container_name}}
        {{container_name}}_docker.docker.docker_container: {{container_name}}
      AUTOKUMA__DOCKER__HOSTS: unix:///var/run/docker.sock
      AUTOKUMA__DOCKER__LABEL_PREFIX: kuma
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/zoemoeremans/docker/services/autokuma/data:/data
    restart: unless-stopped
      
uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /home/zoemoeremans/docker/services/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: unless-stopped
```

Here’s an example service added to Uptime-Kuma via AutoKuma:

```
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/zoemoeremans/docker/services/jellyfin/config:/config
      - /media/external/media/animes:/data/animes:ro
      - /media/external/media/movies:/data/movies:ro
      - /media/external/media/tvshows:/data/tvshows:ro
    ports:
      - 8096:8096
    restart: unless-stopped
    labels:
      - kuma.__docker
```

AutoKuma successfully adds the monitor for Jellyfin, but it fails to load the Docker host configuration properly. Below is a screenshot showing the issue:

[
<img width="1470" alt="Screenshot 2024-12-08 at 15 09 48" src="https://github.com/user-attachments/assets/f7142eed-30e1-46c1-8de6-593e3df42123">
](url)
