### ISSUE TITLE
Basic auth label for monitors

### ISSUE THREAD

**Issue by DrBlury** [BigBoot/AutoKuma#109]
I'm trying to set up autokuma labels on my services which are behind a traefik basic auth middleware. 
Uptime Kuma is not so happy with this and I can add basic auth in the Uptime-Kuma UI. But in good autokuma fashion i'd love to have a monitoring user that can access all the services behind auth middlewares. 
And this would need to be set somewhere. Ideally on the containers to be monitored. 
Example:
```
      kuma.netdata.http.name: "Netdata"
      kuma.netdata.http.url: "https://netdata.mydomain.com/"
      kuma.netdata.http.basic.user: "some_username"
      kuma.netdata.http.basic.pass: "some_password"
```

Is this already supported and I'm missing something? 
If not, consider this a feature request!

**Comment by BigBoot** [comment]
Hi, the correct labels should be:
```yaml
      kuma.netdata.http.name: "Netdata"
      kuma.netdata.http.url: "https://netdata.mydomain.com/"
      kuma.netdata.http.auth: "basic"
      kuma.netdata.http.basic_auth_user: "some_username"
      kuma.netdata.http.basic_auth_pass: "some_password"
```
