### ISSUE TITLE
Notifications don't register, throw an error instead

### ISSUE THREAD

**Issue by Mastermindzh** [BigBoot/AutoKuma#110]
Hey,

I'm trying to add notifications but I keep running into errors.
I eventually tried applying the following labels (straight from the readme), but still receive the error.

```yml
      kuma.mynotificationprovider.notification.name: "This is a Matrix notification provider"
      kuma.mynotificationprovider.notification.active: "true"
      kuma.mynotificationprovider.notification.config: '{"type": "matrix", "accessToken": "XXXXXXXXXXXXXXXXXX", "homeserverUrl": "https://matrix.org", "internalRoomId": "!xxxxxxxxxxxxxxxxxx:matrix.org"}'

      kuma.mymonitor.http.name: "This is a Monitor with a notification provider"
      kuma.mymonitor.http.notification_names: '["mynotificationprovider"]'
      kuma.mymonitor.http.url: "https://example.com"
```

The error that gives:

```
autokuma-1  | WARN [kuma_client::util] Error while parsing notification: data did not match any variant of untagged enum EntityWrapper!
autokuma-1  | WARN [autokuma::sync] Encountered error during sync: Error while trying to parse labels: data did not match any variant of untagged enum EntityWrapper
```

I've also got a docker-compose where you can replicate it:
```yml
services:
  autokuma:
    image: ghcr.io/bigboot/autokuma:master
    restart: unless-stopped
    environment:
      AUTOKUMA__KUMA__URL: http://172.17.0.1:3001
      AUTOKUMA__KUMA__USERNAME: ${KUMA_USERNAME}
      AUTOKUMA__KUMA__PASSWORD: ${KUMA_PASSWORD}
      AUTOKUMA__TAG_NAME: AutoKuma
      AUTOKUMA__TAG_COLOR: "#42C0FB"
      AUTOKUMA__DEFAULT_SETTINGS: |-
        docker.docker_container: {{container_name}}
        http.max_redirects: 10
        *.max_retries: 3
      AUTOKUMA__DOCKER__LABEL_PREFIX: kuma
      AUTOKUMA__MIGRATE: true
    volumes:
      - ./autokuma/autokuma:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kuma

  kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ${APP_DATA}/uptimekuma:/app/data
      # - ${DOCKER_SOCKET}:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: unless-stopped
    labels:
      kuma.mynotificationprovider.notification.name: "This is a Matrix notification provider"
      kuma.mynotificationprovider.notification.active: "true"
      kuma.mynotificationprovider.notification.config: '{"type": "matrix", "accessToken": "XXXXXXXXXXXXXXXXXX", "homeserverUrl": "https://matrix.org", "internalRoomId": "!xxxxxxxxxxxxxxxxxx:matrix.org"}'

      kuma.mymonitor.http.name: "This is a Monitor with a notification provider"
      kuma.mymonitor.http.notification_names: '["mynotificationprovider"]'
      kuma.mymonitor.http.url: "https://example.com"

```

Any help would be appreciated :)
