### ISSUE TITLE
No monitor named "xxx" could be found - when using parent_name for grouping static monitors

### ISSUE THREAD

**Issue by AurimasNav** [BigBoot/AutoKuma#111]
using master branch: `image: ghcr.io/bigboot/autokuma:sha-23287bc`

having few static monitors defined, one of them is a group:

```shell
ls /autokuma/static-monitors/
connectivity-google.json  connectivity.json
```

connectivity.json
```json
{
    "type": "group",
    "name": "connectivity"
}
```

connectivity-google.json

```json
{
    "name": "Google DNS",
    "type": "port",
    "hostname": "8.8.8.8",
    "port": "53",
    "parent_name": "connectivity"
}
```

error in autokuma container:
> WARN [kuma_client::util] [..2025_01_07_08_25_24.1754827397/connectivity-google.json] No monitor named connectivity could be found

env vars:

```yaml
  AUTOKUMA__KUMA__URL: http://uptime-kuma.uptime-kuma
  AUTOKUMA__KUMA__CALL_TIMEOUT: "5"
  AUTOKUMA__KUMA__CONNECT_TIMEOUT: "5"
  AUTOKUMA__DEFAULT_SETTINGS: |- 
    http.max_redirects: 10
    *.max_retries: 3
  AUTOKUMA__ON_DELETE: delete
  AUTOKUMA__DOCKER__ENABLED: "false"
  AUTOKUMA__STATIC_MONITORS: /autokuma/static-monitors/
```
