### ISSUE TITLE
Can't tag monitors in kubernetes via tag_names - data did not match any variant of untagged enum EntityWrapper

### ISSUE THREAD

**Issue by AurimasNav** [BigBoot/AutoKuma#114]
image: ghcr.io/bigboot/autokuma:sha-23287bc

trying to create example monitor:

```yaml
apiVersion: autokuma.bigboot.dev/v1
kind: KumaEntity
metadata:
  name: example
spec:
  config:
    name: Static Json Example
    type: http
    url: https://example.com
    tag_names:
    - name: example_tag
      value: Foobar
```

the actual created resource in kubernetes does not have tag_names properties, it just creates it with empty object:

```yaml
spec:
  config:
    name: Static Json Example
    tag_names:
      - {}
    type: http
    url: https://example.com
```

results in error:
> WARN [kuma_client::util] Error while parsing example: data did not match any variant of untagged enum EntityWrapper!
WARN [autokuma::sources::kubernetes_source] reconcile failed: K8S(FinalizerError(ApplyFailed(LabelParseError("data did not match any variant of untagged enum EntityWrapper"))))

I've also tried to create tag object:

```yaml
apiVersion: "autokuma.bigboot.dev/v1"
kind: KumaEntity
metadata:
  name: tags
spec:
  config: 
    name: example_tag
    color: "#bf0a0a"
    type: tag
```

which I can see created as it is available in monitor add tag dropbox in kuma UI, but it does not resolve the problem above.
