### ISSUE TITLE
max_retries is not applied

### ISSUE THREAD

**Issue by radokristof** [BigBoot/AutoKuma#12]
I have a default configuration for AutoKuma:
```
AUTOKUMA__KUMA__DEFAULT_SETTINGS: >-
docker.docker_container: {{container_name}}
http.max_redirects: 10
http.max_retries: 2
```

But the `max_retries` is not applied, all monitor has `0` retry. I have tried setting the same on an individual monitor as well, same issue.

**Comment by BigBoot** [comment]
Oh looks like this is an error in the readme, can you try the following (the settings have to be separated by a newline):

```yaml
AUTOKUMA__KUMA__DEFAULT_SETTINGS: |-
  docker.docker_container: {{container_name}}
  http.max_redirects: 10
  http.max_retries: 2
```
