### ISSUE TITLE
AUTOKUMA__KUMA__DEFAULT_SETTINGS is not being used

### ISSUE THREAD

**Issue by lsalazarm99** [BigBoot/AutoKuma#13]
I have the following service definition:

```yml
autokuma:
  image: ghcr.io/bigboot/autokuma:latest
  depends_on:
    - uptime-kuma
  environment:
    AUTOKUMA__KUMA__URL: http://uptime-kuma:3001
    AUTOKUMA__KUMA__USERNAME: ${UPTIME_KUMA_USERNAME}
    AUTOKUMA__KUMA__PASSWORD: ${UPTIME_KUMA_PASSWORD}
    AUTOKUMA__KUMA__DEFAULT_SETTINGS: |-
      docker.docker_container: {{container_name}}
      docker.docker_host: 1
      http.max_retries: 3
  labels:
    diun.enable: "true"
    kuma.autokuma.docker.name: AutoKuma
  networks:
    - uptime_kuma_network
  restart: unless-stopped
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
```

When I launch the service, a monitor is created in Uptime Kuma for AutoKuma, but it uses only the settings from the labels (so, without the `docker_container` and `docker_host` settings). If I explicitly add the `docker_container` label, the monitor is created with that setting.

![image](https://github.com/BigBoot/AutoKuma/assets/42286051/a608af08-7e22-48ab-8ae5-e3090c391efd)
