### ISSUE TITLE
{{container_name}} not working

### ISSUE THREAD

**Issue by jordanlambrecht** [BigBoot/AutoKuma#14]
I'm having some issues getting the dynamic variables to work. 

I keep getting this error:
` WARN  autokuma::sync > Encountered error during sync: Encountered errors trying to validate '{{container_name}}': ["Missing property 'name'"]`

Here's my compose file:

```
x-common-service-config: &common-service-config
  environment:
    TZ: ${TZ}
    PUID: ${PUID}
    PGID: ${PGID}
    UMASK: ${UMASK}
  networks:
    - <redacted>
  restart: always

services:
  uptime-kuma:
    <<: *common-service-config
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WEBSOCKET: "true"
    networks:
      <redacted>:
        aliases:
          - kuma
    ports:
      - ${UPTIME_KUMA_PORT}:${UPTIME_KUMA_PORT}
    labels:
      kuma.controltower.group.name: "Control Tower"
      kuma.{{container_name}}.http.name: "Uptime Kuma"
      kuma.{{container_name}}.http.url: "http://kuma:3001"
      kuma.{{container_name}}.http.parent_name: "control-tower"
      kuma.{{container_name}}.docker.parent_name: "control-tower"
      kuma.{{container_name}}.docker.name: "uptime-kuma"
      kuma.{{container_name}}.docker.docker_container: "uptime-kuma"

  autokuma:
    <<: *common-service-config
    image: ghcr.io/bigboot/autokuma:latest
    container_name: autokuma
    restart: unless-stopped
    hostname: autokuma
    environment:
      AUTOKUMA__KUMA__URL: http://kuma:3001
      AUTOKUMA__KUMA__USERNAME: "${ADMIN_USERNAME}"
      AUTOKUMA__KUMA__PASSWORD: "${ADMIN_PASSWORD}"
      AUTOKUMA__URL: http://kuma:3001
      AUTOKUMA__USERNAME: "${ADMIN_USERNAME}"
      AUTOKUMA__PASSWORD: "${ADMIN_PASSWORD}"
      AUTOKUMA__TAG_NAME: AutoKuma
      AUTOKUMA__TAG_COLOR: "#42C0FB"
      AUTOKUMA__DEFAULT_SETTINGS: |-
        docker.docker_container: {{container_name}}
        http.max_redirects: 10
        http.max_retries: 2
      AUTOKUMA__DOCKER__SOCKET: /var/run/docker.sock
      AUTOKUMA__DOCKER__LABEL_PREFIX: kuma
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - uptime-kuma

overseerr:
    <<: *common-service-config
    image: sctx/overseerr:develop
    container_name: overseerr
    hostname: overseerr
    ports:
      - 5055:5055
    volumes:
      - ./overseerr/:/app/config
    labels:
      kuma.mediamanager.group.name: "Media Manager"
      kuma.{{container_name}}.http.name: "Overseerr"
      kuma.{{container_name}}.http.url: "http://overseerr:5055"
      kuma.{{container_name}}.http.parent_name: "media-manager"
      kuma.{{container_name}}.docker.parent_name: "media-manager"
      kuma.{{container_name}}.docker.name: "Overseerr"
      kuma.{{container_name}}.docker.docker_container: "overseerr"
```

It's probably me doing something stupid, but the documentation could really benefit from some more granular instructions and a detailed example docker-compose file. Also there's some conflicting information between the documentation and the release notes for [0.3.0](https://github.com/BigBoot/AutoKuma/releases/tag/v0.3.0), hence the doubling-up on the variables- any advice there would be greatly appreciated.

Love this project!
