### ISSUE TITLE
Issue with creating group

### ISSUE THREAD

**Issue by radokristof** [BigBoot/AutoKuma#17]
I'm still having problems with groups even after the last fix in https://github.com/BigBoot/AutoKuma/issues/8

```
INFO [autokuma::sync] Creating new monitor: bitwarden
WARN [autokuma::sync] Cannot create monitor bitwarden because group vault does not exist
```

The only difference from sample config is that I'm using a custom tag_name: `AutoKumaL01`

The group is indeed there, the name is also correct.

**Comment by radokristof** [comment]
The trick with removing `parent_name` now has different behavior. If I remove it, the monitor will be created (outside of the group of course) but adding it back will just cause another error:
```
INFO [autokuma::sync] Updating monitor: bitwarden
WARN [autokuma::sync] Encountered error during sync: No group named vault could be found
```

**Comment by BigBoot** [comment]
Hmm, looks like I harcoded the kuma label name to `AutoKuma` when resolving groups and forgot to read it from the config.

**Comment by radokristof** [comment]
I just changed it because multiple instances (servers) connect to the same uptime-kuma server. If I don't change it, it will interfere with each other.

**Comment by undaunt** [comment]
@BigBoot I'm still seeing this behavior on latest master. Could it be a combination of other factors?

```
  autokuma:
    image: ghcr.io/bigboot/autokuma:latest
    container_name: autokuma
    restart: unless-stopped
    profiles: ["all","kuma","morty"]
    networks:
      - $PROXY_NETWORK
      - $SOCKET_NETWORK
    depends_on:
      - uptime-kuma
    environment:
      - AUTOKUMA__KUMA__URL=http://uptime-kuma:3001
      - AUTOKUMA__KUMA__USERNAME=${KUMA_USER}
      - AUTOKUMA__KUMA__PASSWORD=${KUMA_PASSWORD}
      - AUTOKUMA__TAG_NAME=autokuma
      - DOCKER_HOST=http://socket-proxy:2375
    labels:
      - kuma.kuma.group.name=Kuma
      - kuma.{{container_name}}.docker.parent_name=kuma
      - kuma.{{container_name}}.docker.name=Autokuma
      - kuma.{{container_name}}.docker.docker_container={{container_name}}
      - kuma.{{container_name}}.docker.docker_host=1
```
