### ISSUE TITLE
Add {{Port}} Template Value

### ISSUE THREAD

**Issue by Nikey646** [BigBoot/AutoKuma#24]
This should be the first port available on a docker container, allowing the construction of the url via label to look like `http://{{container_name}}:{{port}}`, and if the selected port is not the correct one user can just manually specify.

I don't really use rust, but if I had to guess the implementation...

```rs
                    (
                        "port",
                        &container
                            .ports
                            .as_ref()
                            .and_then(|ports| ports.first().map(|p| p.public_port).to_owner()),
                    ),
```

added after around here https://github.com/BigBoot/AutoKuma/blob/master/autokuma/src/sync.rs#L182

This is just blind modifications of the container name code to try and make it somewhat work, so I wouldn't be surprised if it is wrong.

Things of note that I cannot figure out is, filtering down to just TCP ports (HTTP/3 won't be considered here though), and if there is any muckery about type conversion from u16 to string.

**Comment by BigBoot** [comment]
I'm not really a fan of the port thing, it's just way to ambiguous:
- should it be TCP only? Or UDP? Or both?
- Which network interface
- Only exposed ports or also just internal ports
- Should it be the private or the public port
- What even is the "first" port, docker gives this information as a map, so the first would always be the lowest alphanumerical port?

**Comment by BigBoot** [comment]
I've added the ability to define reusable snippets, please take a look at [the Snippets section](https://github.com/BigBoot/AutoKuma?tab=readme-ov-file#snippets), I think this should reduce boilerplate quite a bit while staying flexible enough to work with different setups.

**Comment by BigBoot** [comment]
Accessing ports is now available using the "container" variable which exposed all details about the container, see [the Docker Engine Documentation](https://docs.docker.com/engine/api/v1.45/#tag/Container) for details.

**Comment by mgrimace** [comment]
So using `container` is there a way to construct a 'generic' label that can be applied to all services, such as through the use of anchors that can automatically get the container name and port? (Assuming everything I'd like to add automatically via compose labels is a docker service (e.g., uptime-kuma) with an external:internal port mapped)? Apologies in advance for all the basic questions, I'm learning as I go:

```yaml
x-app: &homelab-default 
  restart: unless-stopped
  security_opt:
    - apparmor:unconfined
  networks:
    - homelab
  environment: &env
    PUID: ${PUID}
    PGID: ${PGID}
    TZ: ${TZ}
  labels: &labels
    com.centurylinklabs.watchtower.enable: "true"
    autokuma.enable: "true" #something here that can be automatically added to all services in the compose stack below? 
  ```
