### ISSUE TITLE
Default Notification support

### ISSUE THREAD

**Issue by undaunt** [BigBoot/AutoKuma#25]
I'm doing some testing and it seems that containers created by Autokuma are not given default 'on' notifications even if my provider (in this case ntfy) is set to 'default enabled' as in the below screenshot.

![image](https://github.com/BigBoot/AutoKuma/assets/31376520/319d9360-3a51-492a-8d34-a44f534126f6)

![image](https://github.com/BigBoot/AutoKuma/assets/31376520/0dd2dd08-f67a-442a-99fb-ec611642d351)

**Comment by BigBoot** [comment]
Hi, yes this is handled using special client side logic by the uptime kuma webui (the same is btw true for proxies) which I don't plan to replicate, however you can achieve basically the same using autokumas `default_settings` config:

```yaml
    environment:
      AUTOKUMA__DEFAULT_SETTINGS: |- 
         *.notification_id_list: { "1": true }
```
