### ISSUE TITLE
Multiple checks for single pod?

### ISSUE THREAD

**Issue by johntdyer** [BigBoot/AutoKuma#38]
Is it possible to define two different checks on a container ?

**Comment by BigBoot** [comment]
Yes, you just need to use different ids for the monitors

```yaml
kuma.monitor_1.http.name: "First Http Monitor"
kuma.monitor_1.http.url: "https://example1.com"
kuma.monitor_2.http.name: "Second Http Monitor"
kuma.monitor_2.http.url: "https://example2.com"
```

**Comment by johntdyer** [comment]
I assume we can have multiple template references in a containers label?

```yaml
labels:
      kuma.__web: '{ "host": "promtail", "port" :9080, "parent_group" : "group-monitoring" "max_retries":3}'
      kuma.__mqtt: '{ "host": "promtail", "port" :1884, "parent_group" : "group-monitoring" "max_retries":3}'
```
