### ISSUE TITLE
Feature Request: adding tags from labels

### ISSUE THREAD

**Issue by ZioPao** [BigBoot/AutoKuma#40]
Hi, I'm loving your work! 
I couldn't find any way to add multiple tags other than setting AUTOKUMA__TAG_NAME.
I would expect to have a way to set specific tags to each container instead of just having that one in all of the managed monitors.

Thank you in advance

**Comment by BigBoot** [comment]
Hello,

the autokuma tag is required for autokuma to function and should not be touched manually, as of now there is no way to create a tag using autokuma, but you can assign existing tags to monitors:

```yaml
labels:
  kuma.example.http.name: "Example"
  kuma.example.http.url: "https://example.com"
  kuma.example.http.tags: '[{"tag_id": 0 }]'
```

To get the id of an existing tag you can use the [kuma CLI](https://github.com/BigBoot/AutoKuma#kuma-cli--)
