### ISSUE TITLE
Support for remote docker hosts?

### ISSUE THREAD

**Issue by zodac** [BigBoot/AutoKuma#50]
Hi, I'm just starting to set up AutoKuma on my home system. Is there any support (currently or planned) for remote docker hosts? I have a couple of machines in my network, and it would be great to be able to use docker labels to configure them too.

**Comment by BigBoot** [comment]
Accessing a remote Docker host is supported by setting the DOCKER_HOST variable accordingly, e.g. `tcp://174.17.0.1:2375`, note that currently there is no support for SSL.

**Comment by BigBoot** [comment]
Yes autokuma only supports a single docker host, so you'd need multiple instances, in which case you probably also want to set `AUTOKUMA__TAG_NAME` to a different tag for each one and increase the sync inverval by setting `AUTOKUMA__SYNC_INTERVAL=30` or something so you won't run into rate limiting issues

**Comment by zodac** [comment]
Hi @BigBoot , sorry to be back so soon. I tried setting this up, but I'm running into errors when reading the labels from my remote host. I've definitely got my remote host exposed and accessed correctly (I use another container to remotely access this host which is working fine, and the AutoKuma error log mentions the container name, which is only exposed by the remote host).

I am just getting the following error:

> WARN [kuma_client::util] Error while parsing uptime-kuma: expected value at line 1 column 1!
> WARN [autokuma::sync] Encountered error during sync: Error while trying to parse labels: expected value at line 1 column 1

My main docker-compose config:

```
  autokuma-pi:
    image: ghcr.io/bigboot/autokuma:0.6.0
    container_name: autokuma-pi
    hostname: autokuma-pi
    environment:
      AUTOKUMA__DEFAULT_SETTINGS: |-
        http.accepted_statuscodes:  [ "200" ]
        http.tags: '[{"tag_id": 4 }]'
        http.expiry_notification: true
        http.interval: 60
        http.max_redirects: 1
        http.max_retries: 5
        http.retry_interval: 60
        http.timeout: 30
      AUTOKUMA__KUMA__URL: "http://192.168.1.1:3001"
      AUTOKUMA__KUMA__USERNAME: "username"
      AUTOKUMA__KUMA__PASSWORD: "password"
      AUTOKUMA__ON_DELETE: "keep" # Keep monitors even if the service goes down
      AUTOKUMA__TAG_NAME: "Docker"
      AUTOKUMA__TAG_COLOR: "#42C0FB"
      DOCKER_HOST: "tcp://192.168.1.1:2375" # Example URL, I use the correct LAN IP address
    volumes:
      # Docker socket mount from host system
      - "${DOCKER_SOCKET}:/var/run/docker.sock"
    ...
```

My remote host docker-compose config:

```
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.13-alpine
    container_name: uptime-kuma
    hostname: uptime-kuma
    labels:
      # Uptime-Kuma monitor config
      kuma.uptime-kuma.http.name: "Uptime Kuma"
      kuma.uptime-kuma.http.url: "https://my.site.com/"
    ...
```

I have more or less the same labels for containers in my main docker-compose, and almost identical autokuma config for the other container.

I didn't see if there was a way to get debug information, but I did run a `docker inspect` on the target container, and the labels seem fine to me:

```
"Labels": {
    "kuma.uptime-kuma.http.name": "Uptime Kuma",
    "kuma.uptime-kuma.http.url": "https://my.site.com/"
}
```

**Comment by BigBoot** [comment]
I think the problem is the default settings:
```yaml
    AUTOKUMA__DEFAULT_SETTINGS: |-
        http.accepted_statuscodes:  [ "200" ]
        http.tags: '[{"tag_id": 4 }]'
        http.expiry_notification: true
        http.interval: 60
        http.max_redirects: 1
        http.max_retries: 5
        http.retry_interval: 60
        http.timeout: 30
```

while they look like kinda like yaml they're just a `<key>:<value` mapping. with both keys and values being strings (so they can be processed in the same way as docker labels). So this means `http.tags: '[{"tag_id": 4 }]'` should be`http.tags: [{"tag_id": 4 }]`
