### ISSUE TITLE
 Error during connect

### ISSUE THREAD

**Issue by 0neTX** [BigBoot/AutoKuma#6]
Running in a local enviroment, Autokuma cannot connect to uptimekuma server.

Execute this docker compose
```yaml
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
  
  autokuma:
    image: ghcr.io/bigboot/autokuma:latest
    restart: unless-stopped
    environment:
      AUTOKUMA__KUMA__URL: http://localhost:3001
      AUTOKUMA__KUMA__USERNAME: userup
      AUTOKUMA__KUMA__PASSWORD: useruptime123
```

Obtain the following error log:

```bash
Attaching to uptime-kuma, autokuma-1
autokuma-1   |
autokuma-1   |                 .:::.                                      .:::.
autokuma-1   |               .===-====:                                :-===--==:
autokuma-1   |              .==.    .:==-.        ..........         :==-.    .==:
autokuma-1   |              -=-        :===--====================---==:        -==
autokuma-1   |              -=-          :===-..              ..:===-          :==
autokuma-1   |              -=-            ::                    .-.           -==
autokuma-1   |              :==                                                ==-
autokuma-1   |               ==.                                              .==.
autokuma-1   |              :==-                                              -==-
autokuma-1   |             .====.                                             ====-
autokuma-1   |             ==-                                                  .==:
autokuma-1   |            :==                                                    ===
autokuma-1   |            -==                                                    -==
autokuma-1   |            -==                                                    :==
autokuma-1   |            -==               ..        ...       ..               -==
autokuma-1   |            .==.             :===     -=====.    ====              ==-
autokuma-1   |             ===              .:.   :==-  :==-    ::              :==.
autokuma-1   |             .==:                  :==:    .==-                  .==:
autokuma-1   |              .==.                :==:      .==-                .==-
autokuma-1   |               .==:              .==:        .==:              .==:
autokuma-1   |                .==-             ==-          :==             :==:
autokuma-1   |                 .-==:          :==            -=-          .-==.
autokuma-1   |                   .===.        ==.   .::::..   ==.       .-==:
autokuma-1   |                     :===.     :=-  ==========. :==     .-==:
autokuma-1   |                       .===:   ==.  -=========  .==.  .-==:
autokuma-1   |                         .-==-:==    .======:    ==-:===:
autokuma-1   |                            :-===:      ...     .====:.
autokuma-1   |                               :==-.          .-==:
autokuma-1   |                                 :====---:--====:
autokuma-1   |                                    .::----::.
autokuma-1   |                             _           _  __
autokuma-1   |               /\           | |         | |/ /
autokuma-1   |              /  \    _   _ | |_   ___  | ' /  _   _  _ __ ___    __ _
autokuma-1   |             / /\ \  | | | || __| / _ \ |  <  | | | || '_ ` _ \  / _` |
autokuma-1   |            / ____ \ | |_| || |_ | (_) || . \ | |_| || | | | | || (_| |
autokuma-1   |           /_/    \_\ \__,_| \__| \___/ |_|\_\ \__,_||_| |_| |_| \__,_|
autokuma-1   |
autokuma-1   |  2024-03-07T19:29:13.697Z ERROR kuma_client::util > Error during connect
uptime-kuma  | ==> Performing startup jobs and maintenance tasks
uptime-kuma  | ==> Starting application with user 0 group 0
uptime-kuma  | Welcome to Uptime Kuma
uptime-kuma  | Your Node.js version: 18.19.0
uptime-kuma  | 2024-03-07T19:29:13Z [SERVER] INFO: Welcome to Uptime Kuma
uptime-kuma  | 2024-03-07T19:29:13Z [SERVER] INFO: Node Env: production
uptime-kuma  | 2024-03-07T19:29:13Z [SERVER] INFO: Inside Container: true
uptime-kuma  | 2024-03-07T19:29:13Z [SERVER] INFO: Importing Node libraries
uptime-kuma  | 2024-03-07T19:29:13Z [SERVER] INFO: Importing 3rd-party libraries
uptime-kuma  | 2024-03-07T19:29:14Z [SERVER] INFO: Creating express and socket.io instance
uptime-kuma  | 2024-03-07T19:29:14Z [SERVER] INFO: Server Type: HTTP
uptime-kuma  | 2024-03-07T19:29:14Z [SERVER] INFO: Importing this project modules
uptime-kuma  | 2024-03-07T19:29:14Z [NOTIFICATION] INFO: Prepare Notification Providers
uptime-kuma  | 2024-03-07T19:29:14Z [SERVER] INFO: Version: 1.23.11
uptime-kuma  | 2024-03-07T19:29:14Z [DB] INFO: Data Dir: ./data/
uptime-kuma  | 2024-03-07T19:29:14Z [SERVER] INFO: Connecting to the Database
uptime-kuma  | 2024-03-07T19:29:14Z [DB] INFO: SQLite config:
uptime-kuma  | [ { journal_mode: 'wal' } ]
uptime-kuma  | [ { cache_size: -12000 } ]
uptime-kuma  | 2024-03-07T19:29:14Z [DB] INFO: SQLite Version: 3.41.1
uptime-kuma  | 2024-03-07T19:29:14Z [SERVER] INFO: Connected
uptime-kuma  | 2024-03-07T19:29:14Z [DB] INFO: Your database version: 10
uptime-kuma  | 2024-03-07T19:29:14Z [DB] INFO: Latest database version: 10
uptime-kuma  | 2024-03-07T19:29:14Z [DB] INFO: Database patch not needed
uptime-kuma  | 2024-03-07T19:29:14Z [DB] INFO: Database Patch 2.0 Process
uptime-kuma  | 2024-03-07T19:29:14Z [SERVER] INFO: Load JWT secret from database.
uptime-kuma  | 2024-03-07T20:29:14+01:00 [SERVER] INFO: Adding route
uptime-kuma  | 2024-03-07T20:29:14+01:00 [SERVER] INFO: Adding socket handler
uptime-kuma  | 2024-03-07T20:29:14+01:00 [SERVER] INFO: Init the server
uptime-kuma  | 2024-03-07T20:29:14+01:00 [SERVER] INFO: Listening on 3001
uptime-kuma  | 2024-03-07T20:29:14+01:00 [SERVICES] INFO: Starting nscd
uptime-kuma  | 2024-03-07T20:29:19+01:00 [SOCKET] INFO: New polling connection, IP = 172.20.0.1
uptime-kuma  | 2024-03-07T20:29:19+01:00 [AUTH] INFO: Login by token. IP=172.20.0.1
uptime-kuma  | 2024-03-07T20:29:19+01:00 [AUTH] INFO: Username from JWT: oindingo
uptime-kuma  | 2024-03-07T20:29:19+01:00 [AUTH] INFO: Successfully logged in user oindingo. IP=172.20.0.1
uptime-kuma  | 2024-03-07T20:29:20+01:00 [SOCKET] INFO: New polling connection, IP = 172.20.0.1
uptime-kuma  | 2024-03-07T20:29:20+01:00 [AUTH] INFO: Login by token. IP=172.20.0.1
uptime-kuma  | 2024-03-07T20:29:20+01:00 [AUTH] INFO: Username from JWT: oindingo
uptime-kuma  | 2024-03-07T20:29:20+01:00 [AUTH] INFO: Successfully logged in user oindingo. IP=172.20.0.1
autokuma-1   |  2024-03-07T19:29:22.708Z WARN  kuma_client::client > Timeout while waiting for Kuma to get ready...
autokuma-1   |  2024-03-07T19:29:22.708Z WARN  autokuma::sync      > Encountered error during sync: Timeout while trying to connect to Uptime Kuma server
autokuma-1   |  2024-03-07T19:29:27.709Z ERROR kuma_client::util   > Error during connect
autokuma-1   |  2024-03-07T19:29:36.719Z WARN  kuma_client::client > Timeout while waiting for Kuma to get ready...
autokuma-1   |  2024-03-07T19:29:36.719Z WARN  autokuma::sync      > Encountered error during sync: Timeout while trying to connect to Uptime Kuma server
autokuma-1   |  2024-03-07T19:29:41.721Z ERROR kuma_client::util   > Error during connect
autokuma-1   |  2024-03-07T19:29:50.732Z WARN  kuma_client::client > Timeout while waiting for Kuma to get ready...
autokuma-1   |  2024-03-07T19:29:50.732Z WARN  autokuma::sync      > Encountered error during sync: Timeout while trying to connect to Uptime Kuma server
autokuma-1   |  2024-03-07T19:29:55.734Z ERROR kuma_client::util   > Error during connect
autokuma-1   |  2024-03-07T19:30:04.744Z WARN  kuma_client::client > Timeout while waiting for Kuma to get ready...
```

**Comment by BigBoot** [comment]
Hi, a docker container cannot access your host network by default, you'll either need to set it to host network mode or preferably set up a network for the two containers:

```yaml
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    networks:
      uptime-kuma:
        aliases:
          - kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
  
  autokuma:
    image: ghcr.io/bigboot/autokuma:latest
    restart: unless-stopped
    networks:
      uptime-kuma:
    environment:
      AUTOKUMA__KUMA__URL: http://kuma:3001
      AUTOKUMA__KUMA__USERNAME: userup
      AUTOKUMA__KUMA__PASSWORD: useruptime123


  networks:
    uptime-kuma:
```
