### ISSUE TITLE
Unable to Start AutoKuma While Using Snippets

### ISSUE THREAD

**Issue by sameleff** [BigBoot/AutoKuma#67]
I'm pretty confident this is a syntax issue, but for the life of me I cannot find it.

Whenever I run autokuma using the below config, I receive the following error: `WARN [kuma_client::util] Error while parsing snippet arguments: expected `:` at line 1 column 18`

```
version: "3.8"
services:
    homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
        - <my volumes here>
    ports:
      - 4000:3000
    labels:
      kuma.__web: '{ "<my local IP>", "4000" }' 
    
    uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptimekuma
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - <my volumes here>

  autokuma:
    image: ghcr.io/bigboot/autokuma:latest
    container_name: autokuma
    restart: unless-stopped
    environment:
      AUTOKUMA__KUMA__URL: http://<my local IP>:3001
      AUTOKUMA__KUMA__USERNAME: <my username>
      AUTOKUMA__KUMA__PASSWORD: <my password>
      AUTOKUMA__DEFAULT_SETTINGS: |- 
         docker.docker_container: {{container_name}}
         http.max_redirects: 10
         *.max_retries: 3
         *.interval: 60
      AUTOKUMA__SNIPPETS__WEB: |- 
         {{container_name}}_http.http.name: {{container_name}} HTTP
         {{ container_name }}_http.http.url: http://{{ args[0] }}:{{ args[1] }}
         {{container_name}}_docker.docker.name: {{container_name}} Docker
         {{container_name}}_docker.docker.docker_container: {{container_name}}
      AUTOKUMA__DOCKER__LABEL_PREFIX: kuma
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
