### ISSUE TITLE
Feature request: add tag by name.

### ISSUE THREAD

**Issue by landure** [BigBoot/AutoKuma#68]
I'm using static monitors feature with a file like:

```toml
type = "http"
name = "Static Toml Example"
url = "https://example.com"
[[tags]]
tag_id=1
value = "example"
[[tags]]
tag_id = 2
value = "other value"
```

Please add a query to Uptime Kuma to get an existing tag ID by its name when a tag `name` is provided by label or by TOML file.
Using `tag_id` isn't very user-friendly.

The file would then be:

```toml
type = "http"
name = "Static Toml Example"
url = "https://example.com"
[[tags]]
name = "My Tag"
value = "example"
[[tags]]
name = "OtherTag"
value = "other value"
```

AutoKuma is great work. Thank you !
