### ISSUE TITLE
Snippet Usage Questions (auto-tagging & docker socket)

### ISSUE THREAD

**Issue by sameleff** [BigBoot/AutoKuma#70]
When creating new monitors via snippets:
1. Tags are automatically created even though `AUTOKUMA_TAG_NAME` and `AUTOKUMA_TAG_COLOR` are not used. Is there a way to disable tagging while using snippets?
2. Docker-type monitors are not linked to the appropriate docker host; docker socket is mounted to both uptime-kuma and autokuma. Once manually configured using the edit menu within Uptime Kuma, the monitor created by the snippet works. How to link a docker monitor created by a snippet to the docker host in Uptime Kuma?

I am running on unraid in case that changes anything.

Here is my config:
```
services:
    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        volumes:
          - /mnt/user/appdata/homepage/config:/app/config
          - /mnt/user/appdata/homepage/icons:/app/public/icons
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 4060:3000
        labels:
          - kuma.__web="<my local IP>", "4060"
    
    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptimekuma
        restart: unless-stopped
        ports:
          - 3001:3001
        volumes:
          - /mnt/user/appdata/uptime-kuma:/app/data
          - /var/run/docker.sock:/var/run/docker.sock

      autokuma:
        image: ghcr.io/bigboot/autokuma:latest
        container_name: autokuma
        restart: unless-stopped
        environment:
          AUTOKUMA__KUMA__URL: http://<my local ip>:3001
          AUTOKUMA__KUMA__USERNAME: <my uptime-kuma user>
          AUTOKUMA__KUMA__PASSWORD: <my uptime-kuma pw>
          # AUTOKUMA__TAG_NAME: AutoKuma
          # AUTOKUMA__TAG_COLOR: "#42C0FB"
          AUTOKUMA__DEFAULT_SETTINGS: |- 
             docker.docker_container: {{container_name}}
             http.max_redirects: 10
             *.max_retries: 3
             *.interval: 60
          AUTOKUMA__SNIPPETS__WEB: |- 
             {{container_name}}.docker.name: {{container_name}}
             {{container_name}}.docker.docker_container: {{container_name}}
          AUTOKUMA__DOCKER__HOSTS: unix:///var/run/docker.sock
          AUTOKUMA__DOCKER__LABEL_PREFIX: kuma
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
```

The monitor connects once I populate the "Docker Host" field in this screenshot.
![image](https://github.com/user-attachments/assets/983d594b-cadf-4deb-8cb6-7b57aec26e56)
