### ISSUE TITLE
attaching a docker monitor to a group fails on creation

### ISSUE THREAD

**Issue by jlewis92** [BigBoot/AutoKuma#8]
These are the labels I have:

```yml
kuma.auth.group.name: "auth"
kuma.lldap.docker.parent_name: "auth"
kuma.lldap.docker.name: "lldap"
kuma.lldap.docker.docker_container: "lldap"
kuma.lldap.docker.docker_host: 1
```

running this causes an error to be thrown in the log:

```
2024-03-09 17:49:41  2024-03-09T17:49:41.599Z INFO  autokuma::sync > Creating new monitor: lldap
2024-03-09 17:49:41  2024-03-09T17:49:41.601Z WARN  autokuma::sync > Encountered error during sync: Server responded with an error: insert into `monitor` (`accepted_statuscodes_json`, `docker_container`, `docker_host`, `interval`, `kafka_producer_brokers`, `kafka_producer_sasl_options`, `name`, `parent`, `parent_name`, `retry_interval`, `type`, `user_id`) values ('["200-299"]', 'lldap', 1, 60, NULL, NULL, 'lldap', 22, 'auth', 60, 'docker', 1) - SQLITE_ERROR: table monitor has no column named parent_name
```

However, I did find a workaround, which is to create the monitor without the group and then attach after creation

i.e.:

```yml
kuma.auth.group.name: "auth"
# kuma.lldap.docker.parent_name: "auth"
kuma.lldap.docker.name: "lldap"
kuma.lldap.docker.docker_container: "lldap"
kuma.lldap.docker.docker_host: 1
```

 `docker compose up -d`

then force an update:

```yml
kuma.auth.group.name: "auth"
kuma.lldap.docker.parent_name: "auth"
kuma.lldap.docker.name: "lldap"
kuma.lldap.docker.docker_container: "lldap"
kuma.lldap.docker.docker_host: 1
```

 `docker compose up -d`
