### ISSUE TITLE
[unreleased] AutoKuma db out of sync due to groups creation not prioritized

### ISSUE THREAD

**Issue by landure** [BigBoot/AutoKuma#92]
Hi,

I was incorrectly using master image. This issue occured:

with the introduction of AutoKuma database, an unwanted behavior appeared (with static monitors)

```toml
# group.toml
type = "group"
name = "My Group"
```

```toml
# alpaga.com.toml
type = "http"
name = "alpaga"
parent_name="group"
url = "https://www.alpaga.com/"
max_retries = 3
retry_interval = 60
notification_id_list = {"1"= true}
```

If `alpaga.com` is created before the group, Uptime Kuma responds with this error:

```log
 WARN [autokuma::sync] Encountered error during sync: Server responded with an error: INSERT INTO monitor_tag (tag_id, monitor_id, value) VALUES (1, 92, 'group') - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
```

`alpaga.com` is created in Uptime Kuma, without parent group, but not stored in AutoKuma database.
AutoKuma will then create several alpaga.com probes, until the creation of the parent group.

This is also the case when the notification is missing.

This behavior was not an issue when AutoKuma based itself on labels to identifys its entries in Uptime Kuma.
