### ISSUE TITLE
[unreleased] Static monitors id is based on path, not on filename

### ISSUE THREAD

**Issue by landure** [BigBoot/AutoKuma#93]
In master image, with

```env
AUTOKUMA__STATIC_MONITORS=/etc/static-monitors
```

This static monitor id isn't `group` but `static-monitors/group`:

```toml
# group.toml
type = "group"
name = "My Group"
```

This is a change of static monitors behavior.
