### ISSUE TITLE
Is it possible to use docker environment variables for substitution in static configuration files?

### ISSUE THREAD

**Issue by instantdreams** [BigBoot/AutoKuma#97]
My aim is to use AutoKuma to store and manage my Uptime-Kuma configuration, which would be kept in a repository.

Part of this [GitOps](https://github.com/readme/featured/defining-gitops) approach is to avoid storing secrets (passwords, tokens, other sensitive information) in a repo but instead using environment files, secrets files, key vaults, or other systems to reference the sensitive information. A good example of a simple implementation of this is the `expand-env` config option for [loki](https://grafana.com/docs/loki/latest/configure/#use-environment-variables-in-the-configuration). It is also available in [frigate](https://docs.frigate.video/configuration/#environment-variable-substitution) for certain values.

The directory containing my autokuma compose, environment, and configuration files would look something like this:

<details><summary>/srv/autokuma/compose.yaml</summary>
<p>

```
services:
  autokuma:
    image: ghcr.io/bigboot/autokuma:master
    container_name: ${CONTAINER_NAME1}
    hostname: ${HOSTNAME1}
    domainname: ${DOMAINNAME}
    environment:
      - AUTOKUMA__DOCKER__ENABLED=${AUTOKUMA__DOCKER__ENABLED}
      - AUTOKUMA__STATIC_MONITORS=${AUTOKUMA__STATIC_MONITORS}
      - AUTOKUMA__LOG_DIR=${AUTOKUMA__LOG_DIR}
      - AUTOKUMA__ON_DELETE=${AUTOKUMA__ON_DELETE}
      - AUTOKUMA__KUMA__URL=${AUTOKUMA__KUMA__URL}
      - AUTOKUMA__KUMA__USERNAME=${AUTOKUMA__KUMA__USERNAME}
      - AUTOKUMA__KUMA__PASSWORD=${AUTOKUMA__KUMA__PASSWORD}
      - AUTOKUMA__KUMA__CALL_TIMEOUT=${AUTOKUMA__KUMA__CALL_TIMEOUT}
      - AUTOKUMA__KUMA__CONNECT_TIMEOUT=${AUTOKUMA__KUMA__CONNECT_TIMEOUT}
    volumes:
      - ${DIRECTORY_DATA}:/data
      - ${DIRECTORY_STATIC}:/autokuma/static
      - ${DIRECTORY_LOGS}:/autokuma/logs
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
```
</p>
</details> 

<details><summary>/srv/autokuma/.env.example</summary>
<p>

```
# Host specifics
CONTAINER_NAME1=autokuma
CONTAINER_PORT1=
HOSTNAME1=autokuma
DOMAINNAME=example.com
# Directory locations
DIRECTORY_DATA=/srv/autokuma/data
DIRECTORY_STATIC=/srv/autokuma/static
DIRECTORY_LOGS=/srv/autokuma/logs
# Container specifics
AUTOKUMA__DOCKER__ENABLED=false
AUTOKUMA__STATIC_MONITORS=/autokuma/static
AUTOKUMA__LOG_DIR=/autokuma/logs
AUTOKUMA__ON_DELETE=keep
AUTOKUMA__KUMA__URL=http://192.168.1.93:3002
AUTOKUMA__KUMA__USERNAME=[username]
AUTOKUMA__KUMA__PASSWORD=[password]
AUTOKUMA__KUMA__CALL_TIMEOUT=15
AUTOKUMA__KUMA__CONNECT_TIMEOUT=30
# Container secrets
AUTOKUMA__MYSQL_USERNAME=[mysql-username]
AUTOKUMA__MYSQL_PASSWORD=[mysql-password]
AUTOKUMA__POSTGRES_USERNAME=[postgres-username]
AUTOKUMA__POSTGRES_PASSWORD=[postgres-password]
AUTOKUMA__TELEGRAM_BOT_TOKEN=[telegram-bot-token]
AUTOKUMA__TELEGRAM_CHAT_ID=[telegram-chat-id]
```
</p>
</details> 

<details><summary>/srv/autokuma/static/database.json</summary>
<p>

```
[
    {
        "type": "group",
        "name": "databases",
        "interval": 120,
        "max_retries": 2,
        "retry_interval": 120,
        "description": "All monitors for databases"
    },
    {
        "type": "postgres",
        "name": "teslamate-db.postgres",
        "parent_name": "static/database[0]",
        "database_connection_string": "postgres://${AUTOKUMA__POSTGRES_USERNAME}:${AUTOKUMA__POSTGRES_PASSWORD}@192.168.1.93:5432/teslamate",
        "database_query": "SELECT datname FROM pg_database WHERE datistemplate = false;"
    },
    {
        "type": "mysql",
        "name": "photoprism-db.mariadb",
        "parent_name": "static/database[0]",
        "database_connection_string": "mysql://${AUTOKUMA__MYSQL_USERNAME}@192.168.1.93:3310/photoprism",
        "radius_password": "${AUTOKUMA__MYSQL_PASSWORD}",
        "database_query": "SHOW DATABASES;"
    }
]
```
</p>
</details> 

<details><summary>/srv/autokuma/static/notification.json</summary>
<p>

```
{
    "type": "notification",
    "active": true,
    "isDefault": true,
    "config":
    {
        "type": "telegram",
        "active": true,
        "isDefault": true,
        "name": "telegram",
        "telegramBotToken": "${AUTOKUMA__TELEGRAM_BOT_TOKEN}",
        "telegramChatID": ${AUTOKUMA__TELEGRAM_CHAT_ID},
        "telegramMessageThreadID": "6",
        "userId": 1
     }
}
```
</p>
</details> 

The steps to stand up the AutoKuma instance would be:
   1. cd /srv/autokuma
   2. cp .env.example .env
   3. nano .env
   4. Replace all [substitution-values] with sensitive data
   5. docker compose up --detach

Then the variable substitution would do the work.

Is this something that AutoKuma can already do? If not, could it be added to the roadmap?
